name: ours

backbone: 
  _target_: src.model.module.manual_extractor.ManualFeatureExtractor
  name: sam_vit_b
  froze_depth: 2
  use_axial_attn: False
  use_selector: True

  selector_config:
    k: 24
    soft: True
    use_gumbel: True
    
    noise_std: 1.0
    noise_std_decay: 0.9999
    min_noise_std: 0.3

    tau: 1.0
    tau_decay: 0.9999
    min_tau: 0.1

  row_selector_config:
    k: 32
    soft: True
    use_gumbel: True

    noise_std: 1.0
    noise_std_decay: 0.9999
    min_noise_std: 0.3

    tau: 1.0
    tau_decay: 0.9999
    min_tau: 0.1