defaults:
  - _self_
  - dataset: tiny_crack
  - aug: adapt_aug
  - loss: ce_smooth_topk
  - model: ours
  - metric: 
      - monitor
      - skl_based
      - iou
      - errmat_based


loader:
  # torch Dataloader zone
  train_loader_params:
    batch_size: 1
    num_workers: 16
    persistent_workers: True
    
  val_loader_params:
    batch_size: 12
    num_workers: 16
    persistent_workers: True

  # customized keywords, should be removed if using regular loader
  train_epoch_splits: null
  train_shuffle: False


optimizer:
  name: Adam
  optimizer_params:
    lr: 0.00008
    weight_decay: 0


scheduler:
  name: OneCycleLR
  scheduler_params:
    div_factor: 2                                      # starts at lr / 10
    pct_start: 0.1                                      # reaches lr at 30% of total steps
    final_div_factor: 2                                # ends at lr / 10 / 10
    max_lr: ${runner.optimizer.optimizer_params.lr}
    epochs: ${runner.trainer.max_epochs}
    steps_per_epoch: ???
    cycle_momentum: False


trainer:
  max_epochs: 600
  log_every_n_steps: 50

  num_nodes: 1
  devices: -1
  precision: 32

  limit_train_batches: 1.0
  limit_val_batches: 1.0
  val_check_interval: 1.0
  num_sanity_val_steps: 0
  check_val_every_n_epoch: ${runner.trainer.accumulate_grad_batches}

  accumulate_grad_batches: 25
  
tags:
  - adapt