defaults:
  - _self_
  - runner: train

exp:
  project: crack_cd_fss_Final
  uuid: ${now:%m%d_%H%M%S}@${exp.cmt}
  cmt: null_comment
  save_dir: ${hydra:runtime.cwd}/logs/${exp.uuid}
  seed: 2025
  n_shot: 1

hydra:
  run:
    dir: ${exp.save_dir}/hydra_output

checkpoint:
  _target_: src.callback.checkpoint.Checkpoint
  output_path: ${exp.save_dir}/checkpoints
  exp_id: ${exp.uuid}
  monitor: mIoU
  topk_models: 1