name: crack_vision_12k
data_path: datasets/CrackVision12k
n_shot: ???
limited_num_val: 200
transform: ???

also_val_at:
  name: tiny_crack
  data_path: datasets/TinyCrack
  n_shot: ???
  limited_num_val: null
  transform: ???